blank_issues_enabled: true
contact_links:
  - name: OsservatorioNessuno General Support
    url: https://osservatorionessuno.org/contacts/
    about: If you need support outside of Bugbane or need to remain private, contact us.
