name: F-Droid

on:
  workflow_call:
    inputs:
      ref_sha:
        required: true
        type: string
      repo_full_name:
        required: true
        type: string
  workflow_dispatch: {}

env:
  TZ: UTC
  LANG: C.UTF-8
  LC_ALL: C.UTF-8
  serverwebroot: /tmp
  APPID: org.osservatorionessuno.bugbane

jobs:
  fdroid-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (exact PR head or push)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: ${{ inputs.repo_full_name }}
          ref: ${{ inputs.ref_sha }}

      - name: Stable env
        run: |
          echo "TZ=UTC" >> $GITHUB_ENV
          echo "LANG=C.UTF-8" >> $GITHUB_ENV
          echo "LC_ALL=C.UTF-8" >> $GITHUB_ENV
          echo "SOURCE_DATE_EPOCH=$(git show -s --format=%ct ${{ inputs.ref_sha }})" >> $GITHUB_ENV

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            git curl locales \
            python3 python3-pip python3-launchpadlib \
            openjdk-17-jdk-headless apksigner mercurial \
            jq unzip diffutils rsync

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platforms;android-36 build-tools;36.0.0

      - name: Install Gradle
        env:
          GRADLE_VERSION: "8.13"
        run: |
          curl -L -o gradle-${GRADLE_VERSION}-bin.zip https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip
          unzip -q gradle-${GRADLE_VERSION}-bin.zip -d "$HOME/gradle"
          echo "$HOME/gradle/gradle-${GRADLE_VERSION}/bin" >> "$GITHUB_PATH"
          gradle --version

      - name: Add fdroidserver to PATH/ENV
        run: |
          git clone --depth 1 https://gitlab.com/fdroid/fdroidserver.git fdroidserver
          cd fdroidserver
          pip install --upgrade pip setuptools wheel
          pip install .
          cd ..
          chmod +x fdroidserver/fdroid
          echo "$GITHUB_WORKSPACE/fdroidserver" >> "$GITHUB_PATH"
          echo "PYTHONPATH=$GITHUB_WORKSPACE/fdroidserver:$GITHUB_WORKSPACE/fdroidserver/examples" >> "$GITHUB_ENV"

      - name: Check fdroid version
        run: fdroid --version

      - name: Determine APPID
        run: |
          if [ "${APPID}" = "org.example.app" ]; then
            APPID=$(ls metadata/*.yml | head -n1 | sed -E 's|metadata/(.*)\.yml|\1|')
          fi
          echo "APPID=$APPID" >> $GITHUB_ENV
          echo "Using APPID=$APPID"

      - name: Prepare full fdroiddata
        env:
          REPO_URL: https://github.com/${{ inputs.repo_full_name }}.git
          PIN: ${{ inputs.ref_sha }}
        run: |
          set -euo pipefail
          TMP_META_DIR="$(mktemp -d)"
          echo "TMP_META_DIR=$TMP_META_DIR" >> $GITHUB_ENV
          mkdir -p "$serverwebroot/repo/status"

          git clone --depth 1 https://gitlab.com/fdroid/fdroiddata.git "$TMP_META_DIR"

          test -f "metadata/${APPID}.yml" || { echo "::error::metadata/${APPID}.yml not found"; exit 1; }
          cp "metadata/${APPID}.yml" "$TMP_META_DIR/metadata/${APPID}.yml"

          cd "$TMP_META_DIR"
          cat > config.yml <<'YAML'
          repo_url: https://example.invalid/repo
          make_current_version_link: false
          gradle: gradle
          cachedir: /tmp/.cache/fdroid
          gradle_version_dir: /home/runner/.gradle/wrapper/dists
          YAML
          chmod 600 config.yml

          APPFILE="$TMP_META_DIR/metadata/${APPID}.yml"

          # Rewrite ONLY the first Repo: and commit: lines (use '|' delimiter + POSIX [[:space:]])
          sed -i -E "0,/^([[:space:]]*Repo:[[:space:]]*).*/ s||\1${REPO_URL}|" "$APPFILE"
          sed -i -E "0,/^([[:space:]]*commit:[[:space:]]*).*/ s||\1${PIN}|" "$APPFILE"

          echo '== After rewrite =='
          grep -nE '^[[:space:]]*(Repo|commit):' "$APPFILE" || sed -n '1,120p' "$APPFILE"

          git -C "$TMP_META_DIR" add "metadata/${APPID}.yml" "config.yml"
          git -C "$TMP_META_DIR" -c user.email=ci@example.invalid -c user.name=CI commit -m "Use custom metadata for ${APPID}" >/dev/null

      - name: F-Droid checkupdates
        run: |
          set -euo pipefail
          cd "$TMP_META_DIR"
          fdroid checkupdates --auto -v "$APPID"

      - name: F-Droid rewritemeta + lint
        run: |
          set -euo pipefail
          cd "$TMP_META_DIR"
          fdroid rewritemeta "$APPID"
          fdroid lint "$APPID"

      - name: Build
        env:
          SOURCE_DATE_EPOCH: ${{ env.SOURCE_DATE_EPOCH }}
        run: |
          set -euo pipefail
          cd "$TMP_META_DIR"
          fdroid build --verbose --no-tarball "$APPID"

      - name: Generate CI keystore and wire it into config.yml
        run: |
          set -euo pipefail
          : "${TMP_META_DIR:?TMP_META_DIR missing}"

          CI_KEYSTORE="$GITHUB_WORKSPACE/ci-two-keys.jks"
          CI_STOREPASS="single-use-ci-storepass"
          CI_KEYPASS="$CI_STOREPASS"
          CI_ALIAS="ci"

          keytool -genkeypair \
            -alias "$CI_ALIAS" \
            -keyalg RSA -keysize 4096 -sigalg SHA256withRSA \
            -validity 36500 \
            -storetype JKS \
            -keystore "$CI_KEYSTORE" \
            -storepass "$CI_STOREPASS" \
            -keypass "$CI_KEYPASS" \
            -dname "CN=CI Repo,O=Example,C=US"

          cd "$TMP_META_DIR"
          {
            echo "keystore: \"$CI_KEYSTORE\""
            echo "keystorepass: \"$CI_STOREPASS\""
            echo "keyalias: \"$CI_ALIAS\""
            echo "keypass: \"$CI_KEYPASS\""
            echo "repo_keyalias: \"$CI_ALIAS\""
            echo "keyaliases:"
            echo "  ${APPID}: \"$CI_ALIAS\""
          } >> config.yml
          chmod 600 config.yml
          echo "==== config.yml ===="
          sed -n '1,160p' config.yml

      - name: Publish
        run: |
          set -euo pipefail
          cd "$TMP_META_DIR"
          fdroid publish --verbose --error-on-failed "$APPID"

      - name: Collect artifacts
        run: |
          set -euo pipefail
          mkdir -p fdroid-out
          rsync -a --ignore-missing-args "$TMP_META_DIR/repo" "$TMP_META_DIR/unsigned" "$TMP_META_DIR/tmp" fdroid-out/ || true
          find "$TMP_META_DIR" -type f \( -name '*.apk' -o -name '*.aab' -o -name 'index.xml' -o -name 'index-v1.json' \) -print0 \
            | xargs -0 -I{} cp --parents {} fdroid-out/ || true
          if [ -d "updated-metadata" ]; then
            rsync -a "updated-metadata/" fdroid-out/updated-metadata/
          fi
          ls -R fdroid-out || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fdroids
          path: fdroid-out/**
          if-no-files-found: error
